#:kivy 2.0.0

<BackdropOptn@SpinnerOption>:
    background_normal: "UI/assets/Toolbar/Adaptive07new.png"
    background_down: "UI/assets/Toolbar/Adaptive07new.png"

<ManagedButton>:
    background_normal: "UI/assets/Toolbar/Adaptive07new.png"
    background_down: "UI/assets/Toolbar/Adaptive07new.png"

<ManagedToggleButton>:
    background_normal: "UI/assets/Toolbar/Adaptive07new.png"
    background_down: "UI/assets/Toolbar/Adaptive07new.png"